logging:
  file:
    name: ./log/backend.log
  level.: WARN

application:
  rest:
    apiPrefix: /api/v1
  authentication:
    signature-algorithm: HS256
    secret: superS3cr3t123
    validity-duration: 31536000
    overlap-duration: 300

security:
  basic:
    enabled: false
    
spring:
  jpa:
    hibernate:
      ddl-auto: update

#######################
### Define profiles ###
#######################
---

spring:
  profiles: development
  profiles.include: development,h2

---

spring:
  profiles: production-h2
  profiles.include: production,h2

---

spring:
  profiles: production-postgres
  profiles.include: production,postgres
