logging:
  file:
    name: ./log/backend.log
  level.: WARN

application:
  rest:
    apiPrefix: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: update

# Define profiles

---

spring:
  profiles: development
    include: development,h2

---

spring:
  profiles: production-h2
    include: production,h2

---

spring:
  profiles: production-postgres
    include: production,postgres
